name: Release

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: "The version suffix for this manual build."
        required: false
  push:
    tags:
      - "v*"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Unix Release (Ubuntu Host)
    env:
      VERSION_SUFFIX: ${{ github.event.inputs.version_suffix }}
    steps:
      - name: Install required packages
        run: sudo apt install -y debhelper dotnet-sdk-8.0 build-essential

      - name: Checkout OpenTabletDriver Repository
        uses: actions/checkout@v4

      - name: Generic Linux Build
        run: ./eng/linux/package.sh --package BinaryTarBall --output ./dist/tarball

      - name: Upload all artifacts (Release)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: OpenTabletDriver v${{ github.ref_name }}
          draft: true
          files: |
            ./dist/tarball/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload generic Linux artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: OpenTabletDriver.linux-x64.tar.gz
          path: ./dist/tarball/*.tar.gz
